### ISSUE TITLE
shippingInstructions mandatory

### ISSUE THREAD

**Issue by nissimsan** [dcsaorg/DCSA-EBL#105]
Elegant that you have include the shippingInstructions within the TransportDoc - that clearly indicates data originating from the shipper versus what is added by the carrier. Well done.
But I suppose `shippingInstruction` should be mandatory, shouldn't it?

**Comment by HenrikHL** [comment]
@nissimsan thanks for noticing this - of course it should be mandatory - this has been fixed in: https://github.com/dcsaorg/DCSA-OpenAPI/pull/70
