### ISSUE TITLE
Missing Cargo-per-Equipment details

### ISSUE THREAD

**Issue by nissimsan** [dcsaorg/DCSA-EBL#106]
During the CEFACT Covid-IFTM project last year we discussed the relationship between Equipment and Cargo. 
You seem to have landed on a model where there is no way to tell, say, that this container contains 25 rolls and that container contains 30 rolls. Only that there are 55 rolls total and two containers.
I'm curious if this is an active decision you have made - if this actually isn’t a requirement, then this is a welcome simplification! I’ve just never seen an old fashioned BL where this isn’t listed out fully.

**Comment by nissimsan** [comment]
Correcting my own point after slacking with @raisoman: 
cargoItems *are* the "atomic" per container amounts (I overlooked `equipmentReference`). 
So changing my comment to just suggest that you include a description on cargoItems attribute to explain this. And explain here also that you need to sum across all the equipment to get the totals.

**Comment by HenrikHL** [comment]
@nissimsan I have updated the cargo Item description + some other descriptions - thanks for noticing
