### ISSUE TITLE
Handle freightPayableAt structure in ShippingInstruction

### ISSUE THREAD

**Issue by nt-as** [dcsaorg/DCSA-EBL#51]
Need clarification on:

 * [ ] How is freight payable related to the ShippingInstruction in the data model? So far the closest match is via Charges but there is a 1:N relation between those and the ShippingInstruction (indirectly via TransportDocument and then we would have to create a basic TD structure immediately).

**Comment by HenrikHL** [comment]
There will be a IM change and a freightPayableAt (type UUID) pointing to a location will be added

**Comment by nt-as** [comment]
Fixed already.
