### ISSUE TITLE
Remove TnT dependency from eBL

### ISSUE THREAD

**Issue by HenrikHL** [dcsaorg/DCSA-EBL#96]
It is a concern that eBL is dependent on TnT in order to send events. This can be solved by:
- [ ] remove callback URL from SI
- [ ] remove callback definition in POST /shipping-instruction (POST will no longer have a callback)
- [ ] add a /document-status/{ID} endPoint in order to return the latest status of the SI/TD
- [ ] change transportDocumentID to be equal to shippingInstructionID (when TD is created it will have the same ID as the SI)

The benefits of this solution is:
* it is possible to only implement eBL (without TnT). In order for client to follow the status of a SI/TD it is necessary for the client to poll on the /document-status/{ID} endPoint
* if the client would like to use a subscription system - the client needs to create this in a different service using the shippingInstructionID

**Comment by nt-as** [comment]
@HenrikHL I think this has been solved now (at least conceptually), hasn't it?

**Comment by HenrikHL** [comment]
Yes - we now have the GET /events endPoint which can be used for polling events. All subscription logic has been removed fro EBL. In order to use the push model - it is necessary to implement one of the Event Hubs - at the time of writing this can either be T&T or DocumentationHub (both support ShipmentEvents)
